### ISSUE TITLE
Comet total magnitude uses PC

### ISSUE THREAD

**Issue by ysBach** [Caltech-IPAC/kete#158]
Currently T-mag has a phase correction using PC:
https://github.com/Caltech-IPAC/kete/blob/a35bf4f5f7e1f369b3edc6f3ce916b699cc9c7e8/src/kete_core/src/flux/comets.rs#L52

As I understand, [Horizons](https://ssd.jpl.nasa.gov/horizons/manual.html#obsquan) does not intend the `PC` value to be used for the T-mag calculation.
```
  Magnitude laws:
    ...
    Comets
      T-mag=M1 + 5*log10(delta) + k1*log10(r)
      N-mag=M2 + 5*log10(delta) + k2*log10(r) + phcof*beta
```

So I guess a correct calculation should use

```rust
Some(m1 + k1 * helio_dist.log10() + 5.0 * obs_dist.log10()) 
```
?

**Comment by dahlend** [comment]
Yeah this was something I spent some time considering when I wrote this. As the total mag by necessity must include the flux contribution from the nucleus, and the nucleus has this correction, it seems incorrect to completely neglect this term in the "T" computation. My compromise was to include this and the user could, as they wished, either set the value to 0 or to any value as desired, to get either behavior. The downside is that you have to call the function twice.

After your comment it is clear to me that this is missing some clarity in the documentation, so I have made a branch which I will merge here in a few minutes which expands out the phase correction term into 2 values, one for the "T" and "N" case. These values will then default to 0.0 and 0.035. This then exactly matches horizons, and enables users to add a phase correction if they believe it is warranted.
